name: ci

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Show variables
        run: |
          echo "repo.default_branch=$repo.default_branch"
          echo "repo.default_branch=${{ repo.default_branch }}"
          echo "github.repository=${{ github.repository }}"
          echo "github.event.repository=${{ github.event.repository }}"
          echo "github.event.repository.default_branch=${{ github.event.repository.default_branch }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
